### ISSUE TITLE
white column in dark mode

### ISSUE THREAD

**Issue by Karmenzind** [gerardbm/vim-atomic#4]
With `set cursorcolumn`

As you can see, the column is too much white...

![image](https://user-images.githubusercontent.com/17923071/70205945-dec56880-1760-11ea-9c96-1e8dee5a4c7d.png)

It's softer in solarized.

![image](https://user-images.githubusercontent.com/17923071/70206063-44195980-1761-11ea-8591-c8b5689ccdc9.png)

**Comment by gerardbm** [comment]
The color of the column is very soft, the same of the cursorline, as in solarized. This is the code:
https://github.com/gerardbm/vim-atomic/blob/master/colors/atomic.vim#L428-L432 (using `s:base2`).

Screenshot using Vim8:
![screenshot-using-vim](https://i.imgur.com/o1DXbq8.png)

However, if the terminal has `gui_running` or `termguicolors`, it will show a blue, cyan, orange or red dark color (`s:base5`, created for this case), depending on the scheme you use.

Screenshot using Gvim (using the `:AtomicDarkBlueSoft`):
![screenshot-using-gvim](https://i.imgur.com/jsYJudp.png)

What I could do is to remove this conditional (L428), remove the colors `s:base5` and simply use the colors of `s:base2` for all (Vim, Gvim, Neovim, and so on). I could do the same with the other components behaving like that, for example the color of the selection.

I will change it. But I would like to know why is it showing a white line on your setup. Curiosity.

**Comment by Karmenzind** [comment]
Thank you.
Maybe you should check `hl-Cursorcolumn`. It's different with `hl-Colorcolumn`.

Here it is:
![image](https://user-images.githubusercontent.com/17923071/70374577-ffdbb400-192e-11ea-87b0-d0414c9eef4d.png)

**Comment by gerardbm** [comment]
Oh, yes. You're right. `CursorColumn` was missing. Thanks! Fixed and closed.

**Comment by Karmenzind** [comment]
Thanks a lot.
