### ISSUE TITLE
colors for YouCompleteMe's signature help

### ISSUE THREAD

**Issue by Karmenzind** [gerardbm/vim-atomic#5]
Hi.

I'm using YouCompleteMe and it can popup [signature help](https://github.com/ycm-core/YouCompleteMe#intro) as below.
[](https://github.com/ycm-core/YouCompleteMe#intro)

![](https://user-images.githubusercontent.com/10584846/58738348-5060da80-83fd-11e9-9537-d07fdbf4554c.gif)

And in solarized it's like:
![image](https://user-images.githubusercontent.com/17923071/82293230-d72c1000-99de-11ea-9c81-eb57a9aa15ea.png)

But in atomic, the parameters are totally invisible:
![image](https://user-images.githubusercontent.com/17923071/82293370-080c4500-99df-11ea-84e9-649bbf9c7816.png)

Hope you can fix the colors. Thank you.

**Comment by gerardbm** [comment]
I installed YCM in a virtual machine, so I can test it there. However, I can't make it work. I installed `python3-dev` and `python3-jedi`, then I compiled YCM with `python3 ./install.py` successfully. How do you open the popup?

Edit: I could open some popus now, with <kbd>Ctrl</kbd>+<kbd>Space</kbd>. It looks fine for me in this case.
![2020-05-23_13:25:31](https://user-images.githubusercontent.com/5253997/82729520-7c552a00-9cf8-11ea-8faf-99d86bb006cb.png)

**Comment by Karmenzind** [comment]
Thanks. It's completion rather than signature help in your picture. And completion works fine here too.
Completion in YCM:
![image](https://user-images.githubusercontent.com/17923071/83380221-fb8ce100-a40f-11ea-9d8c-daf723c0c482.png)

And signature help was triggered after I typed left bracket:
![image](https://user-images.githubusercontent.com/17923071/83380284-2840f880-a410-11ea-8dd5-10b4bc3a8022.png)

I didn't use any hot keys to invoke them.

**Comment by Karmenzind** [comment]
My VIM is 8.2.
I checked my vimrc and find these:
```
set completeopt+=longest,menu
if has('patch-8.1.1902')
    set completeopt+=popup
    set completepopup=height:10,width:60,highlight:Pmenu,border:off
    set pumwidth=10
endif
```
But signature popup still worked after I commented out these lines.

**Comment by gerardbm** [comment]
I can't test the signature help since I couldn't configure YCM. This is a new feature of Vim available only on unstable distros or rolling-releases. I would need more time to install Debian 11 or Arch in a VM.

However, I did some fixes. YCM gets highlighting from syntastic definitions, which I had defined (while solarized does not), so it probably was making a conflict. Update vim-atomic and tell me if it works now. Thanks in advance!

**Comment by Karmenzind** [comment]
Thanks for your help. Sorry it doesn't work.

![image](https://user-images.githubusercontent.com/17923071/90207666-72cfef80-de19-11ea-89c2-635d6fb1a5d2.png)
![image](https://user-images.githubusercontent.com/17923071/90207695-8418fc00-de19-11ea-82a3-57b77997be44.png)

What operating system are you using? Maybe I can help you setup YCM.

**Comment by gerardbm** [comment]
Well, I'm using Debian 9. I had Debian 10 in a VM to test things, so I cloned it and installed YCM on it. Vim version was under 8.1.1875, so I installed Vim again from the sid repositories. However, it was not enough: YCM was unable to load python 3.8. I will download Manjaro i3 to test it.

**Comment by gerardbm** [comment]
Ok, this issue is fixed. Check if it works now. (I installed Manjaro i3 in a VM, with the latest vim version, the latest python version, and it worked very fast. It seems `Pmenu` syntax needs `cterm=reverse`).

**Comment by Karmenzind** [comment]
![image](https://user-images.githubusercontent.com/17923071/90360623-ca2ac580-e08e-11ea-89b9-58b38c88dc93.png)


Good job. Thanks a lot.
